name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: fzlzjerry
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: fzlzjerry
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: '#3584E4'
          color_dots: >
            [
              '#ebedf0',
              '#9be9a8',
              '#40c463',
              '#30a14e',
              '#216e39'
            ]

      # 推送到输出分支
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 